- name: Register K3s Nodes
  hosts: localhost
  gather_facts: no
  tasks:
    - name: "Add K3s nodes to dynamic inventory"
      add_host:
        name: "{{ item.ip }}"
        role: "{{ item.role }}"
      loop: "{{ nodes }}"

- name: Install K3s Cluster
  hosts: all
  tasks:
    - name: K3s Role
      import_role:
        name: K3s

    
      
