- name: Register K3s Nodes
  hosts: localhost
  gather_facts: no
  tasks:
    - name: "Add K3s nodes to dynamic inventory"
      add_host:
        name: "{{ item.ip }}"
        ansible_host: "{{ item.ip }}"
        node_role: "{{ item.role }}"
      loop: "{{ nodes }}"

    - name: "Install K3s for all nodes"
      import_role:
        name: K3s

      
