---
- name: Dynamically generate inventory and install K3s
  hosts: localhost
  tasks:
    - name: Dynamic Inventory
      ansible.builtin.add_host:
        hostname: "{{ item.ip }}"
        groups: "k3s"
        ansible_host: "{{ item.ip }}"
        role: "{{ item.role }}"  # Default role if not provided
        flannel: "{{ item.flannel | default(false) }}"
        kube_proxy: "{{ item.kube_proxy | default(false) }}"
        service_lb: "{{ item.service_lb | default(false) }}"
        traefik: "{{ item.traefik | default(false) }}"
        node_taint: "{{ item.node_taint | default(false) }}"
        cluster_init: "{{ item.cluster_init | default(false) }}"
        network_policy: "{{ item.network_policy | default(false) }}"
        app: "{{ item.app | default([]) }}"
        storage: "{{ item.storage | default([]) }}"
      loop: "{{ nodes }}"
    
- name: Install K3s
  hosts: k3s
  tasks:
    - name: Build K3s installation options
      set_fact:
        k3s_options: >-
          {% if not traefik %}--disable traefik {% endif %}
          {% if not kube_proxy %}--disable kube-proxy {% endif %}
          {% if not service_lb %}--disable servicelb {% endif %}
          {% if not network_policy %}--disable network-policy {% endif %}
          {% if not flannel %}--flannel-backend=none {% endif %}
          {% if not node_taint %}--node-taint 'node-role.kubernetes.io/control-plane:NoSchedule' {% endif %}
          {% if not cluster_init %}--cluster-init{% endif %}

    - name: Install K3s on master node
      shell: |
        curl -sfL https://get.k3s.io | sh -s - server {{ k3s_options }}
      when: item.role == "main"
      loop: "{{ nodes }}"
      become: true
    
      
