- name: Register K3s Nodes
  hosts: localhost
  gather_facts: no
  tasks:
    - name: "Add K3s nodes to dynamic inventory"
      add_host:
        name: "{{ item.ip }}"
        ansible_host: "{{ item.ip }}"
        role: "{{ item.role }}"
      loop: "{{ nodes }}"

- name: Install K3s Cluster
  hosts: all
  tasks:
    - name: Find the Main Master's IP
      set_fact:
        master_ip: "{{ item.ip }}"
      when: role in ['main']
      loop: "{{ nodes }}"

    - name: K3s Role
      import_role:
        name: K3s

    
      
