- name: Install K3s Cluster
  hosts: localhost
  tasks:

    - name: Install K3s Role for Each Node
      include_role:
        name: K3s
      loop: "{{ nodes }}"
      loop_control:
        loop_var: node
