---
- name: pacman
  hosts: all
  connection: local
  gather_facts: false
  any_errors_fatal: true
  tasks:
    - name: Ensure curl is installed
      community.general.pacman:
        name: curl
        state: present
      
