- name: test
  hosts: localhost
  vars:
    host:
      - hostname: "value1"
      - hostname: "value2"
  tasks:

    - name: generate json file from vars
      copy:
        content: "{{ host | to_nice_json }}"
        dest: $HOME/json.json
