- name: test
  hosts: localhost
  vars:
    host:
      - "value1"
      - "value2"
      - "value3"
      - "value4"
  tasks:

    - name: generate json file from vars
      copy:
        content: "{{ [{'hostname': item} , item in host] | to_nice_json }}"
        dest: json.json
      loop: "{{ host }}"
