---
- name: Add master and new workers to the inventory and install K3s
  hosts: localhost
  gather_facts: no
  tasks:      
    - name: Add new master node to the masters group
      add_host:
        groupname: masters
        name: "{{ item.hostname }}"
        ansible_host: "{{ item.ip }}"
        ansible_user: "{{ item.ssh_user }}"
        cluster_init: "{{ item.cluster_init }}"
        #join_cluster: "{{ item.join_cluster | default('') }}"
      loop:
        - { hostname: "master1", ip: "192.168.122.192", ssh_user: "root", cluster_init: true }
        - { hostname: "master2", ip: "192.168.122.35", ssh_user: "root", cluster_init: false } #join_cluster: "192.168.122.192" }
        - { hostname: "master3", ip: "192.168.122.74", ssh_user: "root", cluster_init: false } #join_cluster: "192.168.122.192" }

   
- name: test
  hosts: all
  tasks:
    - name:
      shell: |
        curl -sLS https://get.k3sup.dev | sh
        k3sup install --local {{ '--cluster' if cluster_init else ''}}
