---
- name: Add master and new workers to the inventory and install K3s
  hosts: all
  gather_facts: no
  tasks:      
    - name: Add new master node to the masters group
      add_host:
        groupname: nodes
        name: "{{ item.hostname }}"
        ansible_host: "{{ item.ip }}"
        ansible_user: "{{ item.ssh_user }}"
        cluster_init: "{{ item.cluster_init }}"
        type: "{{ item.type }}"
        join_cluster: "{{ item.join_cluster | default('') }}"
      loop: "{{ k8s }}"

