---
- name: Setup K3s Cluster on Master Nodes
  hosts: localhost
  tasks:

    - name: include master task
      include_tasks: master.yaml
      loop: "{{ master }}"

    - name: Install K3s on worker cluster node
      delegate_to: "{{ worker }}"
      shell: "curl -sfL https://get.k3s.io | sh -s - agent --token {{ k3s_master_token }} --server https://{{ master }}:6443"
      when: "'item' in worker"



