- name: Add master and new workers to the inventory
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Add new master node to the masters group
      add_host:
        name: "{{ item.hostname }}"
        groupname: masters
        ansible_host: "{{ item.ip }}"
        ansible_user: "{{ item.ssh_user }}"
        k3s_install: "{{ item.k3s_install }}"
        cluster-init: "{{ item.cluster_init }}"
      loop: "{{ masters }}"
        # - { hostname: "master1", ip: "192.168.122.192", ssh_user: "root", k3s_install: "true" }
        # - { hostname: "master2", ip: "192.168.122.35", ssh_user: "root", k3s_install: "false" }
        # - { hostname: "master3", ip: "192.168.122.74", ssh_user: "root", k3s_install: "true" }

- name: Install Masters
  hosts: masters
  tasks:
    - name: Install K3s master nodes
      shell: "curl -sfL https://get.k3s.io | sh -s - server --disable traefik {{ '--cluster-init' if cluster_init else '' }}"
      when: k3s_install and cluster-init | bool

    
    # - name: Add new worker nodes to the workers group
    #   add_host:
    #     name: "{{ item.hostname }}"
    #     groups: workers
    #     ansible_host: "{{ item.ip }}"
    #     ansible_ssh_user: "{{ item.ssh_user }}"
    #   loop:
    #     - { hostname: "worker1", ip: "192.168.1.21", ssh_user: "ubuntu" }
    #     - { hostname: "worker2", ip: "192.168.1.22", ssh_user: "ubuntu" }
    #     - { hostname: "worker3", ip: "192.168.1.23", ssh_user: "ubuntu" }


