---
- name: Install K3s on new worker nodes
  hosts: masters
  become: yes
  tasks:
    - name: Install K3s on worker node
      shell: |
        curl -sfL https://get.k3s.io | sh -
      when: install_k3s | bool  # Only install K3s on nodes where install_k3s is true



