---
- name: Setup K3s Cluster on Master Nodes
  hosts: localhost
  tasks:
    - name: K3s Master
      block:
        - name: Installing K3s on master node(s)
          shell: "curl -sfL https://get.k3s.io | sh -s - server --disable traefik --cluster-init"

        - name: Wait until the file /tmp/foo is present before continuing
          ansible.builtin.wait_for:
            path: /var/lib/rancher/k3s/server/node-token

        - name: Extract master token
          command: cat /var/lib/rancher/k3s/server/node-token
          register: master_token

        - name: Set master token as Ansible fact
          set_fact:
            k3s_master_token: "{{ master_token.stdout }}"
      delegate_to: "{{ master }}"


    - name: Install K3s on worker cluster node
      delegate_to: "{{ worker }}"
      shell: "curl -sfL https://get.k3s.io | sh -s - agent --token {{ k3s_master_token }} --server https://{{ master }}:6443"



