---

 ## ### ### ### ### ### ###
### ### ### Vars ### ### ###
 ## ### ### ### ### ### ###
 
- name: Include vars
  ansible.builtin.include_vars:
    dir: vars

 ## ### ### ### ### ### ### ### ##
### ### ### K3s Cluster ### ### ###
 ## ### ### ### ### ### ### ### ##
 
- name: K3s Cluster
  block:
    - name: Download and install k3s
      ansible.builtin.shell: "curl -sfL https://get.k3s.io | sh -s - server {{ ' '.join(k3s_options) }}"
      register: k3s_install_output

    - name: copy k3s config file to user profile
      ansible.builtin.copy:
        src: /etc/rancher/k3s/k3s.yaml
        dest: $HOME/.kube/config
  when: deploy_type['k3s'] is defined

 ## ### ### ### ### ### ### ### ### ###
### ### ### K3s Applications ### ### ###
 ## ### ### ### ### ### ### ### ### ###
 
- name: K3s Applications
  block:
    - name: Add Helm repository for
      kubernetes.core.helm_repository:
        name: "{{ item.namespace }}"
        repo_url: "{{ item.repo_url }}"
      loop: "{{ helm | selectattr('name', 'in', app) }}"

    - name: Deploy Helm chart for
      kubernetes.core.helm:
        name: "{{ item.chart_ref }}"
        chart_ref: "{{ item.chart_ref }}"
        release_namespace: "{{ item.namespace }}"
        create_namespace: true
        values: "{{ lookup('template', '../vars/{{ item.namespace }}.yaml') | from_yaml }}"
      loop: "{{ helm | selectattr('name', 'in', app) }}"
  when: deploy_type['app'] is defined 
  
  
