---
### ### ### Vars ### ### ###
- name: Include vars
  ansible.builtin.include_vars:
    dir: vars

### ### ### K3s Cluster ### ### ###
- name: K3s Cluster
  block:
    - name: Download and install k3s
      shell: "curl -sfL https://get.k3s.io | K3S_KUBECONFIG_MODE=644 sh -s - server {{ ' '.join(k3s_options) }}"
      register: k3s_install_output

    - name: Log k3s installation output
      debug:
        msg: "{{ k3s_install_output.stdout }}"
  when: deploy_type.k3s == "true"

### ### ### K3s Applications ### ### ###
- name: K3s Applications
  block:
    - name: Add Helm repository for
      kubernetes.core.helm_repository:
        name: "{{ item.namespace }}"
        repo_url: "{{ item.repo_url }}"
      loop: "{{ helm | selectattr('name', 'in', app) }}"

    - name: Deploy Helm chart for
      kubernetes.core.helm:
        name: "{{ item.release_name | default(item.chart_ref.split('/')[-1]) }}"
        chart_ref: "{{ item.chart_ref }}"
        release_namespace: "{{ item.namespace }}"
        create_namespace: true
        values: "{{ lookup('template', '../vars/{{ item.namespace }}.yaml') | from_yaml }}"
      loop: "{{ helm | selectattr('name', 'in', app) }}"
  when: deploy_type.app == "true"  
  
  
