# K3s Master Node Installation Task
- name: "==================== Installing K3s Master Node ===================="
  shell: |
    curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="server" sh -s - --cluster-init
  loop: "{{ nodes }}"
  loop_control:
    loop_var: item
  delegate_to: "{{ nodes[0].master }}"

- name: "==================== Extracting K3s Node Token ====================="
  slurp:
    src: /var/lib/rancher/k3s/server/node-token
  register: k3s_token
  loop: "{{ nodes }}"
  loop_control:
    loop_var: item
  when: "{{ nodes[0].master }}"

- name: "==================== Saving Node Token as a Fact ====================="
  set_fact:
    k3s_node_token: "{{ k3s_token.content }}"
    cacheable: true

# K3s Worker Node Installation Task
- name: "==================== Installing K3s Worker Node ====================="
  shell: |
    curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="agent --server https://{{ item.master }}:6443 --token {{ k3s_node_token }}" sh -
  loop: "{{ nodes }}"
  loop_control:
    loop_var: item
  when: "item.worker is defined"
