# K3s Master Node Installation Task
- name: "==================== K3s Setup ===================="
  block:
    - name: "==================== Installing K3s Master Node ===================="
      shell: |
        curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="server" sh -s - --cluster-init

    - name: "==================== Extracting K3s Node Token ====================="
      slurp:
        src: /var/lib/rancher/k3s/server/node-token
      register: k3s_token

    - name: "==================== Saving Node Token as a Fact ====================="
      set_fact:
        k3s_node_token: "{{ k3s_token }}"
        cacheable: true
  when: "item.master is defined"
  loop: "{{ nodes }}"
  delegate_to: "{{ item.master }}"


- name: "==================== Installing K3s Worker Node ====================="
  shell: |
    curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="agent --server https://{{ item.master }}:6443 --token {{ k3s_node_token }}" sh -
  loop: "{{ nodes }}"
  loop_control:
    loop_var: item
  delegate_to: "{{ item.worker }}"
