---
- name: K3s Setup
  when: role in ['main']
  block:
    - name: Installing K3s Cluster
      shell: |
        curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="server" sh -s - --cluster-init

    - name: Extract Token from Master Cluster Node
      slurp:
        src: /var/lib/rancher/k3s/server/node-token
      register: token

    - name: Save Token for Joining Nodes
      set_fact:
        k3s_token: "{{ token.content | b64decode }}"
        cacheable: true

- name: Find the Main Master's IP
  delegate_to: localhost
  set_fact:
    master_ip: "{{ item.ip }}"
  when: role == "main"
  loop: "{{ nodes }}"

- name: Add Master Nodes to HA Cluster
  when: role in ['master']
  shell: |
    curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="server" sh -s - --server {{ master_ip }}:6443 --token {{ hostvars['main'].k3s_token }}

- name: Add Worker Nodes to HA Cluster
  when: role in ['worker']
  shell: |
    curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="agent" sh -s - --server {{ master_ip }}:6443 --token {{ hostvars['main'].k3s_token }}


