---
- name: K3s Setup
  when: item.role == "main"
  block:
    - name: Installing K3s Cluster
      shell: |
        curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="server" sh -s - --cluster-init
      when: cluster == "true"

    - name: Extract Token from Master Cluster Node
      slurp:
        src: /var/lib/rancher/k3s/server/node-token
      register: token

    # - name: Save Token for Joining Nodes
    #   set_fact:
    #     k3s_node_token: "{{ k3s_token }}"
    #     cacheable: true
  

- name: Add Master Nodes to HA Cluster
  shell: |
    curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="server" sh -s - --server {{ item.ip }}:6443 --token "{{ token }}"
  when: item.role == "master"

- name: Add Worker Nodes to HA Cluster
  shell: |
    curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="agent" sh -s - --server {{ item.ip }}:6443 --token "{{ token }}"
  when: item.role == "worker"
