# ================================
#     Install K3s Master Node
# ================================
- name: Install K3s Master
  when: "'master' in item.keys()"
  shell: "curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC='server' sh -"
  loop: "{{ nodes }}"
  loop_control:
    loop_var: item
  delegate_to: "{{ item.master }}"

# ================================
#     Extract Node Token
# ================================
- name: Get K3s Node Token
  when: "'master' in item.keys()"
  slurp:
    src: /var/lib/rancher/k3s/server/node-token
  register: k3s_token
  loop: "{{ nodes }}"
  loop_control:
    loop_var: item
  delegate_to: "{{ item.master }}"
  run_once: true

- name: Save Node Token as a Fact
  when: "'master' in item.keys()"
  set_fact:
    k3s_node_token: "{{ k3s_token.content }}"
    cacheable: true
  run_once: true

# ================================
#     Install K3s Worker Node
# ================================
- name: Install K3s Worker
  when: "'worker' in item.keys()"
  shell: >
    curl -sfL https://get.k3s.io |
    INSTALL_K3S_EXEC="agent --server https://{{ ansible_host }}:6443 --token {{ k3s_node_token }}" sh -
  loop: "{{ nodes }}"
  loop_control:
    loop_var: item
  delegate_to: "{{ item.worker }}"

