---
- name: K3s Setup
  when: role == "main"
  block:
    - name: Installing K3s Cluster
      shell: |
        curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="server" sh -s - --cluster-init

    - name: Extract Token from Master Cluster Node
      slurp:
        src: /var/lib/rancher/k3s/server/node-token
      register: token

    - name: Save Token for Joining Nodes
      set_fact:
        k3s_token: "{{ token.content | b64decode }}"
        cacheable: true
      delegate_to: localhost

- name: Add Master Nodes to HA Cluster
  shell: |
    curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="server" sh -s - --server {{ master_ip }}:6443 --token {{ k3s_token }}
  when: role == "master"

- name: Add Worker Nodes to HA Cluster
  shell: |
    curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="agent" sh -s - --server {{ master_ip }}:6443 --token {{ k3s_token }}
  when: role == "worker"
